services:
  - type: web
    name: ai-safety-incidents-api
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: PORT
        value: 5000
      - key: MONGODB_URI
        fromDatabase:
          name: ai-safety-incidents-db
          property: connectionString 